titleOnly: true
commitsOnly: false
titleAndCommits: false

types:
  - feat
  - fix
  - revert
  - docs
  - style
  - refactor
  - test
  - build
  - security
  - ci
  - chore

scopes:
  - cmd
  - lib
  - others
  - deps

