go1.13:
  image: golang:1.13-buster
  before_script:
    - go version
  script:
    - go build
  only:
    refs:
      - master

go1.14:
  image: golang:1.14-buster
  before_script:
    - go version
  script:
    - go build
  only:
    refs:
      - master

