builds:
  -
    main: ./cmd/lightcable
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge'
      - '^build'
      - '^chore'
      - '^docs'
      - '^test'
      - '^ci'

